import { Amiri } from "next/font/google";
import "./globals.css";

import TransitionProvider from "./_Components/TransitionProvider";

import ContactIcons from "./_Components/ContactIcons";

import LocaleWrapper from "./_Components/LocaleWrapper";
import { LanguageProvider } from "./context/LanguageContext";

export const metadata = {
  title: {
    template: "%s | مكتب احمد عبدالقوى للمحاسبة",
    default: "مكتب احمد عبدالقوى للمحاسبة",
  },
  description: "Generated by create next app",
};

const amiri = Amiri({
  subsets: ["arabic"],
  weight: ["400", "700"],
});

export const revalidate = 0;



export default function RootLayout({ children }) {
  return (
    <LanguageProvider> {/* Ensure this wraps the entire app */}
      <LocaleWrapper>
        <body className={amiri.className}>

          <TransitionProvider amiri={amiri}>{children}</TransitionProvider>
          <ContactIcons />

        </body>
      </LocaleWrapper>
    </LanguageProvider>

  );
}
